### ISSUE TITLE
UX: Testing tab should be better delineated for multiple methods/queries/events.

### ISSUE THREAD

**Issue by goozbach** [Picolab/node-pico-engine#4]
In the testing tab, there are a few lines under the pico's name, one per query/event.

This is a bit confusing, it appears as it is a single form which makes it act in an unexpected way.

![funny form](http://i.imgur.com/pq2maN6.png)

I'm suggesting to make each line look like a single form.
I'll leave it up to you how to do that.

**Comment by 0joshuaolson1** [comment]
This issue was moved to Picolab/pico-engine#146
